In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x = tf.constant(15, dtype='float32')
sess = tf.Session()
print(sess.run(x))

15.0


In [3]:
x = tf.constant(15, dtype='float32')
y = tf.Variable(x + 15)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(y))

30.0


In [4]:
x = tf.placeholder("float", None)
y = x * x + 111
with tf.Session() as sess:
    placeX = sess.run(y, feed_dict={x: [10, 20, 30, 40, 50]})
    print(placeX)

[ 211.  511. 1011. 1711. 2611.]


In [5]:
image = tf.image.decode_jpeg(tf.read_file("apple.jpg"), channels=3)
sess = tf.InteractiveSession()
print(sess.run(tf.shape(image)))

[1758 2790    3]


In [6]:
print(sess.run(image[10:20, 10:20, 1]))

[[126 124 123 122 123 124 122 121 121 121]
 [125 124 123 122 123 124 122 121 122 121]
 [124 124 123 123 122 122 121 121 121 121]
 [123 124 124 124 120 117 120 120 120 120]
 [122 124 125 123 118 114 118 118 119 119]
 [121 124 126 123 117 112 117 117 118 118]
 [120 118 118 118 118 118 121 118 116 116]
 [119 118 118 118 118 119 122 119 116 116]
 [119 118 118 118 119 120 124 121 117 117]
 [119 119 119 120 121 121 125 122 119 118]]


In [7]:
sess = tf.Session()
Zero = tf.zeros([3, 2])
print(sess.run(Zero))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
One = tf.ones([3, 4])
print(sess.run(One))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
C = tf.fill([2, 3], 2)
print(sess.run(C))

[[2 2 2]
 [2 2 2]]


In [10]:
Diag = tf.diag([4, 3, 2, 1])
print(sess.run(Diag))

[[4 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]


In [11]:
Const = tf.constant([1, 4, 6, 8])
print(sess.run(Const))

[1 4 6 8]


In [12]:
Sequance = tf.range(start=3, limit=22, delta=3)
print(sess.run(Sequance))

[ 3  6  9 12 15 18 21]


In [13]:
H = tf.linspace(2, 46, 7)
print(sess.run(H))

[ 2.          9.33333333 16.66666667 24.         31.33333333 38.66666667
 46.        ]


In [14]:
Rand = tf.random_uniform([3, 4], minval=0, maxval=10)
print(sess.run(Rand))

[[3.679074  5.9161735 5.150254  9.868216 ]
 [9.802662  8.84451   6.536599  0.9429443]
 [8.187195  8.938533  7.3258495 2.6620173]]


In [15]:
Rand_norm = tf.random_normal([3, 4], mean=5, stddev=4)
print(sess.run(Rand_norm))

[[ 8.144684   1.777379   6.777107   5.020461 ]
 [ 4.87527    3.0469952 -2.1462264  6.514311 ]
 [ 3.0608635  4.2340364  5.840795  10.6676235]]


In [16]:
tan = tf.nn.tanh([1, 3, 6, -1., 1.5, -6., 2, 3, -10., 2, 9])
print(sess.run(tan))

[ 0.7615942   0.9950547   0.99998784 -0.7615942   0.9051482  -0.99998784
  0.9640276   0.9950547  -1.          0.9640276   1.        ]


In [17]:
sigm = tf.nn.sigmoid([1, 3, 6, -1., 1.5, -6., 2, 3, -10., 2, 9])
print(sess.run(sigm))

[7.3105860e-01 9.5257413e-01 9.9752736e-01 2.6894143e-01 8.1757450e-01
 2.4726233e-03 8.8079709e-01 9.5257413e-01 4.5397868e-05 8.8079709e-01
 9.9987662e-01]


In [18]:
relu = tf.nn.relu([1, 3, 6, -1., 1.5, -6., 2, 3, -10., 2, 9])
print(sess.run(relu))

[1.  3.  6.  0.  1.5 0.  2.  3.  0.  2.  9. ]


Функції втрат

In [19]:
pred = np.asarray([0.1, 2.0, 5.3, 2.1, 1.5, 9.3])
X = tf.convert_to_tensor(pred)
actual = np.asarray([0.2, 1.9, 5.0, 1.1, 1.2, 10.3])

In [20]:
L2 = tf.square(pred-actual)
L2_out = sess.run(tf.round(L2))
print(L2_out)

[0. 0. 0. 1. 0. 1.]


In [21]:
L1 = tf.abs(pred-actual)
L1_out = sess.run(L1)
print(L1_out)

[0.1 0.1 0.3 1.  0.3 1. ]


In [22]:
softmax_xentropy = tf.nn.sigmoid_cross_entropy_with_logits(logits=L1_out, labels=L2_out)
print(sess.run(softmax_xentropy))

[0.74439666 0.74439666 0.85435524 0.31326169 0.85435524 0.31326169]


Оптимізатори

In [23]:
x = tf.Variable(4, name='x', dtype=tf.float32)
log_x = tf.log(x)
log_x_squared = tf.square(log_x)

In [24]:
optimizer = tf.train.GradientDescentOptimizer(0.7)
train = optimizer.minimize(log_x_squared)

In [25]:
init = tf.global_variables_initializer()

In [26]:
with tf.Session() as session:
    session.run(init)
    print("starting at x:", session.run(x), "log(x)^2:", session.run(log_x_squared))
    for step in range(10):
        session.run(train)
        print("step", step, "x:", session.run(x), "log(x)^2:", session.run(log_x_squared))

starting at x: 4.0 log(x)^2: 1.921812
step 0 x: 3.514797 log(x)^2: 1.580003
step 1 x: 3.014121 log(x)^2: 1.217289
step 2 x: 2.501656 log(x)^2: 0.8408027
step 3 x: 1.9885024 log(x)^2: 0.47249374
step 4 x: 1.5045531 log(x)^2: 0.16686891
step 5 x: 1.124444 log(x)^2: 0.013756639
step 6 x: 0.97841257 log(x)^2: 0.0004762804
step 7 x: 1.0096401 log(x)^2: 9.204346e-05
step 8 x: 0.9963368 log(x)^2: 1.3468225e-05
step 9 x: 1.0014936 log(x)^2: 2.2274335e-06


Метрики

In [32]:
x2 = tf.placeholder(tf.int32, [5])
y2 = tf.placeholder(tf.int32, [5])

In [33]:
acc, acc_op = tf.metrics.accuracy(labels=x2, predictions=y2)

In [34]:
sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

In [35]:
val = sess.run([acc, acc_op], feed_dict={x2: [1, 0, 1, 0, 1], y2: [1, 1, 1, 0, 0]})

In [38]:
val_acc = sess.run(acc)
print(val_acc)

0.6
